nameSpace: helm

movie:
  replicaCount: 1
  mountPath: /movie-service/
  hostPath: /app    
  image:
    account: ilhemb
    repository: movie-service
    tag: latest
  service:
    type: NodePort
    protocol: TCP
    port: 8001
    targetPort: 8000
    nodePort: 30001

movieDB:
  replicaCount: 1
  mountPath: postgres_data_movie
  hostPath: /var/lib/postgresql/data/
  image:
    repository: postgres
    tag: 12.1-alpine
  env:
    dbName: movie_db_dev
  service:
    type: ClusterIP
    protocol: TCP
    port: 5432
    targetPort: 5432
    clusterIP: 10.43.60.2

