apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie
  namespace: {{ .Values.nameSpace }}
spec:
  replicas: {{ .Values.movie.replicaCount }}  
  selector:
    matchLabels:
      app: movie
  template:
    metadata:
      labels:
        app: movie
    spec:
      containers:
        - name: movie
          image: {{ .Values.movie.image.account }}/{{ .Values.movie.image.repository }}:{{ .Values.movie.image.tag }}
          command: ['sh', '-c', 'uvicorn app.main:app --reload --host 0.0.0.0 --port 8000']
          ports:
            - containerPort: {{ .Values.movie.service.targetPort }}
          env:
            - name: DATABASE_URI
              value: postgresql://movie_db_username:movie_db_password@{{ .Values.movieDB.service.clusterIP }}/{{ .Values.movieDB.env.movie_db_dev }}
            - name: CAST_SERVICE_HOST_URL
              value: {{ .Values.movieDB.service.clusterIP }}:{{ .Values.movieDB.service.port }}/api/v1/movies/
          volumeMounts:
            - name: movie-volume
              mountPath: {{ .Values.movie.mountPath }}
      volumes:
        - name: movie-volume
          hostPath:
            path: {{ .Values.movie.hostPath }}
      initContainers:
        - name: init-movie
          image: busybox:1.28
          command: ['sh', '-c', 'echo The gateway is running! && sleep 30']                                      
---
apiVersion: v1
kind: Service
metadata:
  name: movie-service
  namespace: {{ .Values.nameSpace }}
spec:
  type: {{ .Values.movie.service.type }}
  selector:
    app: movie
  ports:
    - protocol: {{ .Values.movie.service.protocol }}
      port: {{ .Values.movie.service.port }}
      targetPort: {{ .Values.movie.service.targetPort }}
  clusterIP: {{ .Values.movie.service.clusterIP }}      
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-db
  namespace: {{ .Values.nameSpace }}
spec:
  replicas: {{ .Values.movieDB.replicaCount }}
  selector:
    matchLabels:
      app: movie-db
  template:
    metadata:
      labels:
        app: movie-db
    spec:
      containers:
        - name: movie-db
          image: {{ .Values.movieDB.image.repository }}:{{ .Values.movieDB.image.tag }}
          ports:
            - containerPort: {{ .Values.movieDB.service.targetPort }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: movie-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: movie-secret
                  key: password
            - name: POSTGRES_DB
              value: {{ .Values.movieDB.env.dbName }}
          volumeMounts:
            - name: movie-volume
              mountPath: {{ .Values.movieDB.mountPath }}
      volumes:
        - name: movie-volume
          hostPath:
            path: {{ .Values.movieDB.hostPath }}
---
apiVersion: v1
kind: Service
metadata:
  name: movie-db-service
  namespace: {{ .Values.nameSpace }}
spec:
  type: {{ .Values.movieDB.service.type }}
  selector:
    app: movie-db
  ports:
    - protocol: {{ .Values.movieDB.service.protocol }}
      port: {{ .Values.movieDB.service.port }}
      targetPort: {{ .Values.movieDB.service.targetPort }}
  clusterIP: {{ .Values.movieDB.service.clusterIP }}      