apiVersion: v1
kind: Secret
metadata:
  name: movie-secret
  namespace: {{ .Values.nameSpace }}
type: kubernetes.io/basic-auth
stringData:
  username: 'movie_db_username'
  password: 'movie_db_password'
